### ISSUE TITLE
No dynamic libs available in 1.3.6

### ISSUE THREAD

**Issue by JanuszL** [conda-forge/libvorbis-feedstock#12]
Issue:
1.3.6 conda build doesn't ship dynamic (*.so) libraries anymore. Only static one *.a.

<br/>
Environment (<code>conda list</code>):
<details>

NA
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

NA
</details>

**Comment by dschreij** [comment]
Darn, this has probably gone wrong with libflac then too... Thanks for notifying!

**Comment by dschreij** [comment]
@martinRenou Do you see the chance to quickly change this in your local repo? Since you've done the latest work on these repo's, you probably have all the recent commits at hand. The only changes that I see that need to happen are changing:
```
-DBUILD_SHARED_LIBS=ON 
```
to `OFF` in the build scripts and ${SHLIB_EXT} to the static counterpart in the test section of the meta.yaml.

**Comment by martinRenou** [comment]
Yes, this issue should be fixed by #11, I made a mistake during the 1.3.6 release.

The fixed build of 1.3.6 should be available on conda. 

> Darn, this has probably gone wrong with libflac then too

I made sure to **not** make the mistake twice, I think libflac is going to be fine.

**Comment by JanuszL** [comment]
@martinRenou - I see some improvement - dynamic libs are there, but libvorbis.so.0 is missing and apparently libsndfile.so, relies on it. Only libvorbis.so and libvorbis.so.0.4.8 are there (same for libvorbisenc and libvorbisfile).

**Comment by martinRenou** [comment]
This might need a patch on the official Vorbis CMakeList I guess. I'll see what I can do.

**Comment by martinRenou** [comment]
Let's see if #13 fixes the missing `so` files

**Comment by martinRenou** [comment]
Yes it looks like it fixes it
```
-- Installing: $PREFIX/lib/pkgconfig/vorbis.pc
-- Installing: $PREFIX/lib/pkgconfig/vorbisenc.pc
-- Installing: $PREFIX/lib/pkgconfig/vorbisfile.pc
-- Installing: $PREFIX/include/vorbis/codec.h
-- Installing: $PREFIX/include/vorbis/vorbisenc.h
-- Installing: $PREFIX/include/vorbis/vorbisfile.h
-- Installing: $PREFIX/lib/libvorbis.so.0
-- Installing: $PREFIX/lib/libvorbis.so.0.4.8
-- Installing: $PREFIX/lib/libvorbis.so
-- Installing: $PREFIX/lib/libvorbisenc.so.2
-- Installing: $PREFIX/lib/libvorbisenc.so.2.0.11
-- Set runtime path of "$PREFIX/lib/libvorbisenc.so.2" to ""
-- Installing: $PREFIX/lib/libvorbisenc.so
-- Installing: $PREFIX/lib/libvorbisfile.so.3
-- Installing: $PREFIX/lib/libvorbisfile.so.3.3.7
-- Set runtime path of "$PREFIX/lib/libvorbisfile.so.3" to ""
-- Installing: $PREFIX/lib/libvorbisfile.so
```

**Comment by martinRenou** [comment]
I will try and upstream this fix in the vorbis library

**Comment by dschreij** [comment]
Whoa, it seems I completely misinterpreted the issue. You meant the dynamic libraries were missing while they should be there. Apologies for that. Luckily @martinRenou was sharp ;)

**Comment by martinRenou** [comment]
No worries :)

**Comment by JanuszL** [comment]
It looks that it works now as it should. Thanks for the quick fix!

**Comment by martinRenou** [comment]
Sure! Sorry for breaking it in the first place! I was fixing an issue I had on Windows, but introduced those issues doing it. I hope everything is fine now.

**Comment by JanuszL** [comment]
> Sure! Sorry for breaking it in the first place! I was fixing an issue I had on Windows, but introduced those issues doing it. I hope everything is fine now.

Happens. Don't worry.
